### ISSUE TITLE
手机打开白屏

### ISSUE THREAD

**Issue by Cray-Bear** [luoyangC/vue-mall-template#2]

**Comment by Cray-Bear** [comment]
部署到局域网手机打开白屏WEB端正常

**Comment by lishenli1994** [comment]
To solve the white screen problem.
To update the version in package.json and to add cross-domain and then solve it.
In the follow:
1 package.json:
"dependencies": {
    "axios": "^0.18.0",
    "core-js": "^2.6.5",
    "dayjs": "^1.7.7",
    "js-cookie": "^2.2.0",
    "vant": "^2.0.3",
    "vue": "^2.5.10",
    "vue-i18n": "^7.8.0",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@babel/register": "^7.5.5",
    "@vue/cli-plugin-babel": "^3.0.1",
    "@vue/cli-plugin-eslint": "^3.0.1",
    "@vue/cli-service": "^3.0.1",
    "babel-eslint": "^10.0.1",
    "babel-plugin-import": "^1.12.0",
    "chalk": "^2.4.2",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "less": "^3.9.0",
    "less-loader": "^5.0.0",
    "mockjs": "^1.0.1-beta3",
    "postcss-px-to-viewport": "^1.1.0",
    "style-resources-loader": "^1.2.1",
    "vue-template-compiler": "^2.5.13"
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]

2 axios.js
const config = {
  baseURL: 'http://192.168.1.104:8080',
  timeout: 60 * 1000
}

3 vue.config.js
proxy: {
      // 配置代理服务器
      [process.env.VUE_APP_BASE_API]: {
        target: `http://192.168.1.104:8080/mock`,
        changeOrigin: true,
        pathRewrite: {
          ['^' + process.env.VUE_APP_BASE_API]: ''
        }
      }
    }
